# Generated by Django 3.2.9 on 2021-12-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200)),
                ('redirect', models.CharField(max_length=200)),
                ('create_time', models.IntegerField()),
            ],
        ),
    ]
