# Generated by Django 3.2.10 on 2021-12-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_auto_20211210_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='cnt',
            field=models.IntegerField(default=0),
        ),
    ]
